
<script src="{{asset('AdminDesktops/plugins/jquery/jquery.min.js')}}"></script>
<script src="{{asset('AdminDesktops/plugins/jquery-ui/jquery-ui.min.js')}}"></script>
<script src="{{asset('AdminDesktops/plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
<script src="{{asset('AdminDesktops/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js')}}"></script>
<script src="{{asset('AdminDesktops/plugins/select2/js/select2.full.min.js')}}"></script>
<script src="{{asset('AdminDesktops/plugins/datatables/jquery.dataTables.js')}}"></script>
<script src="{{asset('AdminDesktops/plugins/datatables-bs4/js/dataTables.bootstrap4.js')}}"></script>
<script src="{{asset('AdminDesktops/plugins/datatables-responsive/js/dataTables.responsive.min.js')}}"></script>
<script src="{{asset('AdminDesktops/plugins/datatables-responsive/js/responsive.bootstrap4.min.js')}}"></script>
<script src="{{asset('AdminDesktops/plugins/jquery-validation/jquery.validate.min.js')}}"></script>
<script src="{{asset('AdminDesktops/plugins/jquery-validation/additional-methods.min.js')}}"></script>
<script src="{{asset('AdminDesktops/plugins/moment/moment.min.js')}}"></script>
<script src="{{asset('AdminDesktops/plugins/inputmask/jquery.inputmask.min.js')}}"></script>
<script src="{{asset('AdminDesktops/plugins/daterangepicker/daterangepicker.js')}}"></script>
<script src="{{asset('AdminDesktops/plugins/sweetalert2/sweetalert2.min.js')}}"></script>
<script src="{{asset('AdminDesktops/plugins/toastr/toastr.min.js')}}"></script>
<script src="{{asset('AdminDesktops/dist/js/adminlte.js')}}"></script>
<script> var wallet_total = "{{route('wallet_total')}}"; </script>
<script src="{{asset('app/desktops/main.min.js')}}"></script>